### ISSUE TITLE
Input files for gen_topo

### ISSUE THREAD

**Issue by adele-morrison** [COSIMA/domain-tools#1]
Are there any scripts / documentation for creating the input files (specifically `mosaic.nc`, `ocean_mosaic.nc`, and `ocean_hgrid.nc`) that are needed to run gen_topo?

For the PanAntarctic config, I found `ocean_mosaic.nc`, and `ocean_hgrid.nc` in `/g/data/ik11/inputs/mom6/panan-01/`. But for new regional configs in the future, others will need to know how to create these from scratch. I also haven't found a `mosaic.nc` file for the PanAntarctic config yet.

**Comment by micaeljtoliveira** [comment]
Ping @aekiss

**Comment by aidanheerdegen** [comment]
While we're pinging people @russfiedler would have some knowledge about this, but broadly these tools exist, but I have never used them.

https://github.com/mom-ocean/MOM5/tree/master/src/tools

@russfiedler may have more experience.


Edit: I take that back. I once converted an old style grid to the newer mosaic format. Firmly lodged in my forgettery, and of no real use in any case.

**Comment by russfiedler** [comment]
I'd have a look at FRE-NCtools for updated versions. Minimal documentation but may be enough for your needs.

https://github.com/NOAA-GFDL/FRE-NCtools

**Comment by micaeljtoliveira** [comment]
After looking into the source code of `gen_topo`, it seems the only information it needs from `mosaic.nc` and `ocean_mosaic.nc` is the path and filename of the horizontal grid, which is always `ocean_hgrid.nc` for the ACCESS-OM2 topographies.

I wonder if there is a good reason to use the  `mosaic.nc` and `ocean_mosaic.nc` instead of simply given the horizontal grid as an command line argument to `gen_topo`.

**Comment by micaeljtoliveira** [comment]
The latest version of the tools only require the horizontal grid. Instructions to create the horizontal grid are provided elsewhere. So I think we can close this issue.
